site_name: Energy Modelling Ireland

theme:
  name: material

plugins:
    - redirects:
        redirect_maps:
            'index.md': 'https://energy-modelling-ireland.github.io/ireland-energy-wiki/index.html'